### PR TITLE
HC-439: Purge datasets v1.2.0 job time out after new pcm deployment

### PR DESCRIPTION
**Pull request by DustinKLo**
related ticket: https://hysds-core.atlassian.net/browse/HC-439

change(s):
- removing ES doc deletion from the `multiprocessing` function
  - using the [bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-bulk.html) to purge docs
  - multiprocessing will only be used to delete objects from s3
- returning only necessary fields when querying Elasticsearch
  - speed up read operations
  - ES docs can be very large
  - smaller log size

example of job details:
```
Datasets purged from ES:
grq_v1.0_hello_world - 4
```

### `purge.log`
```log
WARNING:root:the JSON object must be str, bytes or bytearray, not dict
INFO:elasticsearch:POST http://100.104.10.248:9200/grq/_search?_source=dataset%2Curls&size=100 [status:200 request:0.004s]
INFO:elasticsearch:POST http://100.104.10.248:9200/grq/_search?_source=dataset%2Curls&size=100&from=100 [status:200 request:0.003s]
INFO:elasticsearch:POST http://100.104.10.248:9200/grq/_bulk?filter_path=items.delete.error.reason%2Citems.delete._id%2Citems.delete._index%2Citems.delete.result [status:200 request:0.006s]
INFO:root:{
  "items": [
    {
      "delete": {
        "_index": "grq_v1.0_hello_world",
        "_id": "hello_world-product-20221025T175706.236359823Z-7e84e",
        "result": "deleted"
      }
    },
    {
      "delete": {
        "_index": "grq_v1.0_hello_world",
        "_id": "hello_world-product-20221025T175706.317053441Z-f6a89",
        "result": "deleted"
      }
    },
    {
      "delete": {
        "_index": "grq_v1.0_hello_world",
        "_id": "hello_world-product-20221025T175706.236454935Z-38b50",
        "result": "deleted"
      }
    },
    {
      "delete": {
        "_index": "grq_v1.0_hello_world",
        "_id": "hello_world-product-20221025T175706.236444714Z-e6f20",
        "result": "deleted"
      }
    }
  ]
}
INFO:root:purging datasets from object store: 
INFO:osaka:Removing s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236359823Z-7e84e
INFO:osaka:Removing URI s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236359823Z-7e84e
INFO:osaka:Removing s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.317053441Z-f6a89
INFO:osaka:Removing URI s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.317053441Z-f6a89
INFO:osaka:Removing s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236454935Z-38b50
INFO:osaka:Removing URI s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236454935Z-38b50
INFO:osaka:Removing s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236444714Z-e6f20
INFO:osaka:Removing URI s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236444714Z-e6f20
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:osaka:Making session with: {"region_name": "us-#####-#"}
INFO:osaka:Making session with: {"region_name": "us-#####-#"}
INFO:osaka:Making session with: {"region_name": "us-#####-#"}
INFO:osaka:Making session with: {"region_name": "us-#####-#"}
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:botocore.credentials:Found credentials from IAM Role: ########
INFO:osaka:Checking lock status of s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236454935Z-38b50 in s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236454935Z-38b50.osaka.locked.json
INFO:osaka:Checking lock status of s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236359823Z-7e84e in s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236359823Z-7e84e.osaka.locked.json
INFO:osaka:Checking lock status of s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.317053441Z-f6a89 in s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.317053441Z-f6a89.osaka.locked.json
INFO:osaka:Checking lock status of s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236444714Z-e6f20 in s3://s3-us-#####-#.amazonaws.com:80/#######-#####/products/hello_world/v1.0/2022/10/25/hello_world-product-20221025T175706.236444714Z-e6f20.osaka.locked.json
INFO:root:Purged from object store hello_world-product-20221025T175706.236359823Z-7e84e
INFO:root:Purged from object store hello_world-product-20221025T175706.236454935Z-38b50
INFO:root:Purged from object store hello_world-product-20221025T175706.317053441Z-f6a89
INFO:root:Purged from object store hello_world-product-20221025T175706.236444714Z-e6f20
INFO:root:deleted from ES: hello_world-product-20221025T175706.236359823Z-7e84e
INFO:root:deleted from ES: hello_world-product-20221025T175706.317053441Z-f6a89
INFO:root:deleted from ES: hello_world-product-20221025T175706.236454935Z-38b50
INFO:root:deleted from ES: hello_world-product-20221025T175706.236444714Z-e6f20
```

### CODE REVIEW

**Comment by DustinKLo** [comment]
@pymonger @mcayanan i noticed when purging from s3, `osaka` will check for the locked status, what should we do in situations where the `.lock.json` still exists in s3

after testing i saw that it went ahead and purged from s3 + delete the documents from elasticsearch, but i think this edge case behavior has always been there, even before my changes
Screen Shot 2022-10-20 at 4 09 57 PM

## purge.log
```log
INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.869252307Z-44665 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.869252307Z-44665.osaka.locked.json
INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.870047273Z-13442 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.870047273Z-13442.osaka.locked.json
INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230807.082234479Z-b8fbc in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230807.082234479Z-b8fbc.osaka.locked.json   # <----- HERE
INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.989609157Z-baf41 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.989609157Z-baf41.osaka.locked.json
INFO:root:Purged from object store hello_world-product-20221020T230806.989609157Z-baf41
INFO:root:Purged from object store hello_world-product-20221020T230806.869252307Z-44665
INFO:root:Purged from object store hello_world-product-20221020T230807.082234479Z-b8fbc  # <------ HERE
INFO:root:Purged from object store hello_world-product-20221020T230806.870047273Z-13442
```

**Comment by DustinKLo** [comment]
feel free to test @jimmie

**Comment by mcayanan** [comment]
> @pymonger @mcayanan i noticed when purging from s3, `osaka` will check for the locked status, what should we do in situations where the `.lock.json` still exists in s3
> 
> after testing i saw that it went ahead and purged from s3 + delete the documents from elasticsearch, but i think this edge case behavior has always been there, even before my changes Screen Shot 2022-10-20 at 4 09 57 PM
> 
> ## purge.log
> ```
> INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.869252307Z-44665 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.869252307Z-44665.osaka.locked.json
> INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.870047273Z-13442 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.870047273Z-13442.osaka.locked.json
> INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230807.082234479Z-b8fbc in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230807.082234479Z-b8fbc.osaka.locked.json   # <----- HERE
> INFO:osaka:Checking lock status of s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.989609157Z-baf41 in s3://s3-us-west-2.amazonaws.com:80/nisar-dev-lts-fwd-dustinlo/products/hello_world/v1.0/2022/10/20/hello_world-product-20221020T230806.989609157Z-baf41.osaka.locked.json
> INFO:root:Purged from object store hello_world-product-20221020T230806.989609157Z-baf41
> INFO:root:Purged from object store hello_world-product-20221020T230806.869252307Z-44665
> INFO:root:Purged from object store hello_world-product-20221020T230807.082234479Z-b8fbc  # <------ HERE
> INFO:root:Purged from object store hello_world-product-20221020T230806.870047273Z-13442
> ```

I would say to leave this behavior in for now. I think the lock status is meant to prevent multiple workers from publishing to the same place. I think in the case of purge, it would seem like lock files wouldn't necessarily matter as the intent is to delete stuff. Having said that, I'm OK if we wanted to change this behavior to prevent datasets with lock files from being purged. Perhaps the best course of action would be to capture this in a separate ticket and we can resolve later?

**Comment by DustinKLo** [comment]
> I would say to leave this behavior in for now. I think the lock status is meant to prevent multiple workers from publishing to the same place. I think in the case of purge, it would seem like lock files wouldn't necessarily matter as the intent is to delete stuff. Having said that, I'm OK if we wanted to change this behavior to prevent datasets with lock files from being purged. Perhaps the best course of action would be to capture this in a separate ticket and we can resolve later?

i agree, the `.osaka.locked.json` is only there during publish and it gets deleted immediately when finished
the only case where i see it still exist is when the worker dies during publish, but that makes the datasets worth deleting anyways

**Comment by pymonger** [comment]
@DustinKLo @mcayanan: agree on both points.
@DustinKLo: could you run through the end to end tests once more just to make sure the last 2 updates are vetted? thanks.

**Comment by DustinKLo** [comment]
@pymonger  how should i run the dev-e2e? we currently use a released version of `lightweight-jobs` (v1.2.0) so i dont think a regular dev-e2e run can test these changes
there also might be a lot of kluges, in mozart's user rules json, etc.

**Review by pymonger — APPROVED** [review]

**Pull request merged**
